name: base_env

dependencies:
  - python=3.6.*
  - pip
  - pip:
      - azureml-sdk[explain,automl,notebooks]==1.0.83
      - azureml-dataprep[fuse,pandas]>=1.1.19
      - azureml-contrib-pipeline-steps
      - inference-schema[numpy-support]
      - scipy==1.4.1
      - scikit-learn==0.20.3
      - joblib==0.14.1
      - pandas==0.23.4
      - numpy==1.16.2
