name: base_env

dependencies:
  - python=3.6.2
  - pandas==0.23.4
  - numpy==1.16.2
  - scipy==1.4.1
  - scikit-learn==0.20.3
  - joblib==0.14.1
  - pip
  - pip:
      - inference-schema[numpy-support]==1.0.2
      - azureml-sdk[explain,automl,notebooks]==1.0.83
      - azureml-dataprep[fuse,pandas]>=1.1.19
      - azureml-contrib-pipeline-steps
