name: base_env

dependencies:
  - python=3.7
  - pandas=1.0.*
  - numpy=1.18.*
  - joblib=0.14.*
  - pip=20.0.*
  - pip:
      - azureml-sdk==1.6.*
      - azureml-defaults==1.6.*
      - inference-schema[numpy-support]==1.0.*
