name: base_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pandas=1.0.*
  - numpy=1.18.*
  - scipy=1.4.*
  - scikit-learn=0.22.*
  - joblib=0.14.*
  - pip=20.0.*
  - pip:
      - azureml-sdk==1.8.*
