jobs:
  - job: CodeQuality
    displayName: Run Linting, Unit Tests and Code Coverage

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add Conda to PATH

      - script: |
          conda env create \
          --file $(Build.SourcesDirectory)/${{ parameters.conda_dependencies_file}} \
          --name code-quality \
          --quiet
        displayName: Create Anaconda Environment

      - bash: |
          source activate code-quality
          pip install flake8 pytest pytest-cov pytest-azurepipelines --quiet
          python -m flake8 --output-file lint-testresults.xml --format junit-xml
          pytest tests --cov . --cov-report html --cov-report xml --junitxml junit/test-results.xml --doctest-modules
        displayName: Run Linting, Unit Tests, and  Code Coverage
      # - task: PublishTestResults@2
      #   displayName: "Publish Test Results"
      #   condition: succeededOrFailed()
      #   inputs:
      #     testResultsFiles: "**/test-*.xml"
      #     testRunTitle: "Publish test results for Python $(python.version)"
      # - task: PublishCodeCoverageResults@1
      #   displayName: "Publish Coverage Report"
      #   condition: succeededOrFailed()
      #   inputs:
      #     codeCoverageTool: Cobertura
      #     summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.xml"
      #     reportDirectory: "$(System.DefaultWorkingDirectory)/**/htmlcov"
      #     failIfCoverageEmpty: true
