jobs:
  - job: code_quality
    displayName: Code Quality

    variables:
      - template: ./variables.yml

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python 3.7.*
        inputs:
          versionSpec: 3.7.*

      - task: Bash@3
        displayName: Install Dependencies
        inputs:
          targetType: "inline"
          script: |
            pip3 install -r $(dependencies_test)

      - task: Bash@3
        displayName: Run Linting
        inputs:
          targetType: "inline"
          script: |
            python3 -m flake8 .

      - task: Bash@3
        displayName: Run Unit Tests and  Code Coverage
        inputs:
          targetType: "inline"
          script: |
            python3 -m pytest tests/unit \
            --cov scripts \
            --cov-report xml \
            --junitxml junit/test-results.xml

      - task: PublishTestResults@2
        displayName: Publish Test Results
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: $(System.DefaultWorkingDirectory)/**/test-*.xml
          testRunTitle: Publish test results for Python $(python.version)

      - task: PublishCodeCoverageResults@1
        displayName: Publish Coverage Report
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
          failIfCoverageEmpty: true
