jobs:
  - job: CodeQuality
    displayName: Run Linting, Unit Tests and Code Coverage

    steps:
      - script: |
          flake8 \
          --output-file=lint-testresults.xml \
          --format junit-xml
        displayName: "Run Linting"

      - script: |
          python -m pytest . \
          --cov=scripts \
          --cov-report=html \
          --cov-report=xml \
          --junitxml=unit-testresults.xml
        condition: succeededOrFailed()
        displayName: "Run Unit Tests"

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: "*-testresults.xml"
          testRunTitle: "Linting & Unit Tests"
          failTaskOnFailedTests: true
        displayName: "Publish Test Results"

      - task: PublishCodeCoverageResults@1
        displayName: "Publish Coverage Report"
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "coverage.xml"
          reportDirectory: "htmlcov"
          failIfCoverageEmpty: true
