jobs:
  - job: deploy_model
    displayName: ${{ upper( parameters.compute_type ) }} Deployment

    variables:
      - template: ./variables.yml
      - name: service_name
        value: ${{ parameters.service_name }}
      - name: compute_type
        value: ${{ parameters.compute_type }}
      - name: deployment_config
        value: ${{ parameters.deployment_config }}
      - name: inference_config
        value: ${{ parameters.inference_config }}
        ${{ if ne( parameters.compute_target, '' ) }}:
          compute_target_cli: --compute-target ${{ parameters.compute_target }}

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Model Metadata Artifact
        inputs:
          source: current
          artifactName: model-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Deploy to ${{ upper( parameters.compute_type ) }}
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model deploy \
            --name $SERVICE_NAME \
            --compute-type $COMPUTE_TYPE \
            --deploy-config-file $DEPLOYMENT_CONFIG \
            --inference-config-file $INFERENCE_CONFIG \
            --model-metadata-file $(Pipeline.Workspace)/model-metadata/model.json \
            --workspace-name $WORKSPACE_NAME \
            --resource-group $RESOURCE_GROUP \
            $(compute_target_cli) \
            --overwrite
