jobs:
  - job: deploy_model
    displayName: ${{ upper( parameters.compute_type ) }} Deployment

    variables:
      - template: ./variables.yml
      - name: service_name
        value: ${{ parameters.service_name }}

      - name: compute_type
        value: ${{ parameters.compute_type }}

      - name: deployment_config
        value: ${{ parameters.deployment_config }}

      - name: compute_target
        value: ${{ parameters.compute_target }}

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Model Metadata Artifact
        inputs:
          source: current
          artifactName: model-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Set Default Workspace
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml folder attach \
            --workspace-name $(workspace_name) \
            --resource-group $(resource_group)

      - task: AzureCLI@2
        displayName: Deploy to ${{ upper( parameters.compute_type ) }}
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model deploy \
            --name $(service_name) \
            --compute-type $(compute_type) \
            --deploy-config-file $(deployment_config) \
            --inference-config-file $(inference_config) \
            --model-metadata-file $(Pipeline.Workspace)/model-metadata/model.json \
            --compute-target $(compute_target) \
            --overwrite
            --verbose
