jobs:
  - job: DeployModel
    displayName: ${{ upper( parameters.compute_type ) }} Deployment

    variables:
      ${{ if ne( parameters.compute_target, '' ) }}:
        compute_target_cli: --compute-target ${{ parameters.compute_target }}
      ${{ if ne( parameters.location, '' ) }}:
        location_cli: --location ${{ parameters.location }}

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: ${{ parameters.service_connection }}
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Model Metadata Artifact
        inputs:
          source: current
          artifactName: ${{ parameters.model_metadata_artifact }}
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Deploy to ${{ upper( parameters.compute_type ) }}
        inputs:
          scriptType: bash
          azureSubscription: ${{ parameters.service_connection }}
          scriptLocation: inlineScript
          inlineScript: |
            az ml model deploy \
            ${{ variables.compute_target_cli }} \
            ${{ variables.location_cli }} \
            --name ${{ parameters.service_name }} \
            --compute-type ${{ parameters.compute_type }} \
            --deploy-config-file ${{ parameters.deployment_config }} \
            --inference-config-file ${{ parameters.inference_config }} \
            --model-metadata-file $(Pipeline.Workspace)/${{ parameters.model_metadata_artifact }}/model.json \
            --overwrite \
            --resource-group ${{ parameters.resource_group }} \
            --workspace-name ${{ parameters.workspace_name }}
