jobs:
  - job: register_model
    displayName: Register Model
    dependsOn: train_model

    variables:
      - template: ./variables.yml
      - name: input_data
        value:

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Model Metadata Artifact
        inputs:
          source: current
          artifactName: model-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Register Model
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model profile \
            --name model-profile-test \
            --conda-file environments/conda_dependencies_score.yml \
            --inference-config-file config/inference_config.yml \
            --model-metadata-file model-2.json \
            --resource-group sandbox-real-time-deployment-template \
            --workspace-name amlworkspace \
            --input-data

      - task: PublishBuildArtifacts@1
        displayName: Publish Profile Metadata Artifact
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/model.json
          artifactName: profile-metadata
