jobs:
  - job: register_model
    displayName: Register Model
    dependsOn: train_model

    variables:
      - template: ./variables.yml

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(SERVICE_CONNECTION)
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download Run Metadata Artifact
        inputs:
          source: current
          artifactName: run-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Register Model
        inputs:
          scriptType: bash
          azureSubscription: $(SERVICE_CONNECTION)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model register \
            --name $MODEL_NAME \
            --asset-path outputs/model \
            --experiment-name $EXPERIMENT_NAME \
            --output-metadata-file model.json \
            --resource-group $RESOURCE_GROUP \
            --run-metadata-file $(Pipeline.Workspace)/run-metadata/run.json \
            --workspace-name $WORKSPACE_NAME \

      - task: PublishBuildArtifacts@1
        displayName: Publish Model Metadata Artifact
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/model.json
          artifactName: model-metadata
