parameters:
  - name: service_connection
  - name: resource_group_name
  - name: workspace_name

jobs:
  - job: register_model
    displayName: Register Model
    dependsOn: train_model

    variables:
      - template: ./variables.yml

    steps:
      - task: AzureCLI@2
        displayName: Install azure-cli-ml
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: DownloadBuildArtifacts@0
        displayName: Download run metadata artifact
        inputs:
          artifactName: $(run_artifact_name)

      - task: AzureCLI@2
        displayName: Register model
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml model register \
            --name $(model_name) \
            --asset-path $(model_asset_path) \
            --experiment-name $(train_experiment_name) \
            --output-metadata-file $(model_metadata_file) \
            --workspace-name $(workspace_name) \
            --resource-group $(resource_group_name) \
            --run-metadata-file $(run_metadata_file_path)

      - task: PublishBuildArtifacts@1
        displayName: Publish model metadata artifact
        inputs:
          pathToPublish: $(model_metadata_file)
          artifactName: $(model_artifact_name)
