parameters:
  - name: service_connection
  - name: resource_group_name
  - name: workspace_name

jobs:
  - job: train_model
    displayName: Train and register model

    variables:
      - template: ../variables.yml

    steps:
      - task: AzureCLI@2
        displayName: Install azure-cli-ml
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az extension add -n azure-cli-ml

      - task: AzureCLI@2
        displayName: Attach workspace
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az ml folder attach --workspace-name $(workspace_name) --resource-group $(resource_group_name)

      - task: AzureCLI@2
        displayName: Create run config
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Fail on error
            set -e

            # Get dataset metadata
            DATASET_METADATA=$(az ml dataset show --name $(dataset_name) --query registration) 

            # Create run configuration to use for training script
            cat $(train_run_config) | jq -r ".data.InputDataset.dataLocation.dataset |= $DATASET_METADATA" > $(generated_train_run_config).runconfig

      - task: AzureCLI@2
        displayName: Train model
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml run submit-script \
            --run-configuration-name $(generated_train_run_config) \
            --source-directory $(source_directory) \
            --experiment-name $(train_experiment_name) \
            --output-metadata-file $(run_metadata_file) $(train_script) \
            --MODEL_NAME $(model_name) \
            --BUILD_ID $(Build.BuildId)

      - task: AzureCLI@2
        displayName: Get model metadata
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Retreive model for this build from workspace
            az ml model list --tag build_id=$(Build.BuildId) --query '[0]' > $(model_metadata_file)

      - task: PublishBuildArtifacts@1
        displayName: Publish model metadata artifact
        inputs:
          pathToPublish: $(model_metadata_file)
          artifactName: $(model_artifact_name)
