jobs:
  - job: train_model
    displayName: Train Model
    dependsOn: code_quality

    variables:
      - template: ./variables.yml

    steps:
      - task: AzureCLI@2
        displayName: Install Azure ML CLI
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: "az extension add -n azure-cli-ml"

      - task: AzureCLI@2
        displayName: "Train Model"
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            az ml run submit-script \
            --workspace-name $WORKSPACE_NAME \
            --resource-group $RESOURCE_GROUP \
            --experiment-name $EXPERIMENT_NAME \
            --conda-dependencies $DEPENDENCIES_TRAIN \
            --target $AML_COMPUTE_TARGET \
            --source-directory scripts \
            --output-metadata-file run.json train.py \
            --DATASET_NAME $DATASET_NAME

      - task: PublishBuildArtifacts@1
        displayName: Publish Run Metadata Artifact
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/run.json
          artifactName: run-metadata
