name: build_release - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - master
    exclude:
      - docs/*
      - LICENSE
      - README.md

variables:
  - group: aml-deployment-templates
  - template: variables.yml
  - name: resource_group_name
    value: $(environment)-$(namespace)-rg
  - name: workspace_name
    value: mlw$(environment)$(namespace)

stages:
  - stage: code_quality
    displayName: Code Quality
    jobs:
      - template: ./templates/code-quality.yml

  - stage: model_build
    displayName: Model Build
    jobs:
      - template: ./templates/train-register.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          resource_group_name: ${{ variables.resource_group_name }}
          workspace_name: ${{ variables.workspace_name }}

  - stage: deploy_test
    displayName: Test Deployment
    dependsOn: model_build
    jobs:
      - deployment: Approval
        displayName: Test deployment approval
        environment: Test
      - template: ./templates/deploy.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          resource_group_name: ${{ variables.resource_group_name }}
          workspace_name: ${{ variables.workspace_name }}
          service_name: ${{ variables.aci_service_endpoint_name }}
          deployment_config: ${{ variables.aci_deployment_config }}
          compute_type: aci
          environment: Test
      - template: ./templates/smoke-test.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          resource_group_name: ${{ variables.resource_group_name }}
          workspace_name: ${{ variables.workspace_name }}
          service_name: ${{ variables.aci_service_endpoint_name }}

  - stage: deploy_production
    displayName: Production Deployment
    dependsOn: deploy_test
    jobs:
      - deployment: Approval
        displayName: Production deployment approval
        environment: Production
      - template: ./templates/deploy.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          resource_group_name: ${{ variables.resource_group_name }}
          workspace_name: ${{ variables.workspace_name }}
          compute_target: ${{ variables.aks_cluster_name }}
          service_name: ${{ variables.aks_service_endpoint_name }}
          deployment_config: ${{ variables.aks_deployment_config }}
          compute_type: aks
          environment: Production
