name: main pipeline - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: "ubuntu-latest"
variables:
  - template: ./templates/variables.yml
trigger:
  branches:
    include:
      - master
      - releases/*
    exclude:
      - docs/*
      - LICENSE
      - README.md

stages:
  - stage:
    displayName: Code Quality
    jobs:
      - template: ./templates/code-quality.yml
        parameters:
          dependencies_file: ${{ variables.DEPENDENCIES_TEST_FILE }}
          source_directory: ${{ variables.SOURCE_DIRECTORY }}

  - stage:
    displayName: Train Model
    jobs:
      - template: ./templates/train.yml
        parameters:
          service_connection: ${{ variables.SERVICE_CONNECTION }}
          resource_group: ${{ variables.RESOURCE_GROUP }}
          workspace_name: ${{ variables.WORKSPACE }}
          model_name: ${{ variables.MODEL_NAME }}
          experiment_name: ${{ variables.EXPERIMENT_NAME }}
          run_metadata_artifact: ${{ variables.RUN_METADATA_ARTIFACT }}
          dataset_name: ${{ variables.DATASET_NAME }}
          aml_compute_cluster: ${{ variables.AML_COMPUTE_CLUSTER }}
          conda_dependencies_file: ${{ variables.CONDA_DEPENDENCIES_TRAIN_FILE }}
          source_directory: ${{ variables.SOURCE_DIRECTORY }}
          entry_script: ${{ variables.ENTRY_SCRIPT }}

  - stage:
    displayName: Register Model
    jobs:
      - deployment: Approval
        displayName: Model Registration & Test Deployment Approval
        environment: Test
      - template: ./templates/register.yml
        parameters:
          service_connection: ${{ variables.SERVICE_CONNECTION }}
          resource_group: ${{ variables.RESOURCE_GROUP }}
          workspace_name: ${{ variables.WORKSPACE }}
          model_name: ${{ variables.MODEL_NAME }}
          experiment_name: ${{ variables.EXPERIMENT_NAME }}
          model_description: ${{ variables.MODEL_DESCRIPTION }}
          model_framework: ${{ variables.MODEL_FRAMEWORK }}
          model_framework_version: ${{ variables.MODEL_FRAMEWORK_VERSION }}
          run_metadata_artifact: ${{ variables.RUN_METADATA_ARTIFACT }}
          model_metadata_artifact: ${{ variables.MODEL_METADATA_ARTIFACT }}

  - stage:
    displayName: Test Deployment
    jobs:
      - template: ./templates/deploy.yml
        parameters:
          service_connection: ${{ variables.SERVICE_CONNECTION }}
          resource_group: ${{ variables.RESOURCE_GROUP }}
          workspace_name: ${{ variables.WORKSPACE }}
          service_name: ${{ variables.ACI_SERVICE_ENDPOINT_NAME }}
          model_metadata_artifact: ${{ variables.MODEL_METADATA_ARTIFACT }}
          compute_target: ${{ variables.ACI_COMPUTE_TARGET }}
          inference_config: ${{ variables.INFERENCE_CONFIG }}
          deployment_config: ${{ variables.ACI_DEPLOYMENT_CONFIG }}
          compute_type: aci

  - stage:
    displayName: Production Deployment
    jobs:
      - deployment: Approval
        displayName: Production Deployment Approval
        environment: Production
      - template: ./templates/deploy.yml
        parameters:
          service_connection: ${{ variables.SERVICE_CONNECTION }}
          resource_group: ${{ variables.RESOURCE_GROUP }}
          workspace_name: ${{ variables.WORKSPACE }}
          service_name: ${{ variables.AKS_SERVICE_ENDPOINT_NAME }}
          model_metadata_artifact: ${{ variables.MODEL_METADATA_ARTIFACT }}
          compute_target: ${{ variables.AKS_COMPUTE_TARGET }}
          inference_config: ${{ variables.INFERENCE_CONFIG }}
          deployment_config: ${{ variables.AKS_DEPLOYMENT_CONFIG }}
          compute_type: aks
