name: main pipeline - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: "ubuntu-latest"
variables:
  - template: ./templates/variables.yml
trigger:
  branches:
    include:
      - master
      - releases/*
    exclude:
      - docs/*
      - LICENSE
      - README.md

stages:
  - stage: model_build
    displayName: Model Build
    jobs:
      - template: ./templates/code-quality.yml
      - template: ./templates/train.yml
      - template: ./templates/register.yml

  - stage: deploy_test
    displayName: Test Deployment
    jobs:
      - deployment: Approval
        displayName: Test Deployment Approval
        environment: Test
      - template: ./templates/deploy.yml
        parameters:
          compute_type: aci

  - stage: deploy_production
    displayName: Production Deployment
    jobs:
      - deployment: Approval
        displayName: Production Deployment Approval
        environment: Production
      - template: ./templates/deploy.yml
        parameters:
          compute_type: aks
