name: build_release - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: ubuntu-latest

variables:
  - template: ./templates/variables.yml

trigger:
  branches:
    include:
      - master
    exclude:
      - docs/*
      - LICENSE
      - README.md

stages:
  - stage: model_build
    displayName: Model Build
    jobs:
      - template: ./templates/code-quality.yml
      - template: ./templates/train.yml
      - template: ./templates/register.yml

  - stage: deploy_test
    displayName: Test Deployment
    dependsOn: model_build
    jobs:
      - deployment: Approval
        displayName: Test Deployment Approval
        environment: Test
      - template: ./templates/deploy.yml
        parameters:
          compute_type: aci
          service_name: $(aci_service_endpoint_name)
          deployment_config: $(aci_deployment_config)
      - template: ./templates/smoke-test.yml
        parameters:
          service_name: $(aci_service_endpoint_name)

  - stage: deploy_production
    displayName: Production Deployment
    dependsOn: deploy_test
    jobs:
      - deployment: Approval
        displayName: Production Deployment Approval
        environment: Production
      - template: ./templates/deploy.yml
        parameters:
          compute_type: aks
          compute_target: $(aks_cluster_name)
          service_name: $(aks_service_endpoint_name)
          deployment_config: $(aks_deployment_config)
