name: build_release - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: ubuntu-latest
variables:
  - template: ./templates/variables.yml

trigger:
  branches:
    include:
      - master
      - release-*
    exclude:
      - docs/*
      - LICENSE
      - README.md

stages:
  - stage:
    displayName: Model Build
    jobs:
      - template: ./templates/code-quality.yml
      - template: ./templates/train.yml
      - template: ./templates/register.yml

  - stage:
    displayName: Production Deployment
    jobs:
      - deployment: Approval
        displayName: Production Deployment Approval
        environment: Production
      - template: ./templates/deploy.yml
        parameters:
          compute_type: aks
          compute_target: $(aks_compute_target)
          service_name: $(aks_service_endpoint_name)
          deployment_config: $(aks_deployment_config)
